name: Terraform CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: eu-west-2
  LAMBDA_FILE_NAME: lambda_function_payload.zip

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip unzip
          pip3 install boto3 sagemaker pandas pyyaml
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

  pipeline:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Install Python libraries
        run: pip3 install boto3 sagemaker pandas pyyaml

      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Run pipeline scripts
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: |
          python3 ./pipeline_scripts/train_monitor_pipeline.py
          python3 ./pipeline_scripts/hpo_with_monitor_pipeline.py
          python3 ./pipeline_scripts/inference_with_monitor_pipeline.py

  validate:
    runs-on: ubuntu-latest
    needs: pipeline
    steps:
      - uses: actions/checkout@v3

      - name: Install zip tool
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Create Lambda function zip
        run: |
          cd code/lambda_function
          zip -j ../../${{ env.LAMBDA_FILE_NAME }} index.py

      - name: Validate Terraform configuration
        run: |
          terraform init
          terraform validate

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3

      - name: Install jq (for Terraform action)
        run: sudo apt-get update && sudo apt-get install -y jq

      -
